### ISSUE TITLE
Use Flutter Flame - app/use-flutter-flame

### ISSUE THREAD

**Issue by lakscastro** [lakscastro/unbounded#3]
### Current status

[Currently we can handle snake game logic well.](https://github.com/LaksCastro/unbounded/projects/1#card-68146054) But we are not able yet to merge with Game UI and Game Loop. As we know, it's not trivial tasks, so we can use Flutter Flame, a Engine that already implement Game API's, after all, Flutter Flame is the more stable Flutter Game engine.

### Checklist

We need just to research about how to implement the main game features and screens using Flutter Flame for now.

- [x] Save current implementation to know how to implement the Snake Game logic
- [x] Create a new Flutter Flame project
- [x] Start to play with Flame game API's
- [x] Then we can start to draw the screens, starting by the Menu screen as described in #2.
- [x] Migrate the current menu screen codebase to the #2 branch and add only abstract implementations related to Flutter Flame on this current branch. Reason: lets keep everything about Flutter Flame learning curve at this branch and keep everything related to Menu screen feature on #2
- [x] Research about soundtrack transition across the pages (Flutter Flame context)
  - [x] Open a PR/Branch/Comment to implement Fade transition on `audioplayers` package
- [x] Research about page transition across the pages (Flutter Flame context)

### Error/Bug Fixes

- [x] Android build not working: [Flutter Execution failed for task ':audioplayers:compileDebugKotlin'.](https://stackoverflow.com/questions/65558023/flutter-execution-failed-for-task-audioplayerscompiledebugkotlin) Solution: [upgrade `ext.kotlin_version`](https://github.com/bluefireteam/audioplayers/issues/810#issuecomment-803472997)

### Notes/Resources

**Song Transitions**

- [Library used by Flame to handle audio](https://pub.dev/packages/audioplayers)
- [Web Audio API  that implement Fade](https://developer.mozilla.org/en-US/docs/Web/API/AudioParam/linearRampToValueAtTime) used by [Howler Dart Package Wrapper](https://github.com/gmpassos/howler.dart/blob/master/lib/src/howler_base.dart#L1664)
- [Custom Howler Fade audio transition implementation](https://github.com/gmpassos/howler.dart/blob/master/lib/src/howler_base.dart#L1691)
- Custom Howler Fade audio transition implementation for [`audioplayers` package](https://github.com/bluefireteam/audioplayers/issues/945#issuecomment-939288673)

**Comment by lakscastro** [comment]
so long, simplify it!
